[versions]
cloudVersion = "2.0.0-beta.10"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version = "1.21.11-R0.1-SNAPSHOT" }
cloudPaper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloudVersion" }
cloudMinecraftExtras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloudVersion" }
brigadier = { group = "com.mojang", name = "brigadier", version = "1.0.18" }
jacksonbukkit = { group = "de.eldoria.jacksonbukkit", name = "paper", version = "2.0.0" }

[plugins]
resourceFactory = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version = "1.3.1" }
runPaper = { id = "xyz.jpenilla.run-paper", version = "3.0.2" }
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }

[bundles]
cloud = ["cloudPaper", "cloudMinecraftExtras"]